### ISSUE TITLE
[BUG] NullPointerException in MainLauncher.java // run in linux

### ISSUE THREAD

**Issue by Ricardo272727** [ComplexRalex/Completed-Games-Registers#1]
**To Reproduce**
1. Go to 'src/'
2. javac MainLauncher.java
3. java MainLauncher

**Screenshots**
![Captura de pantalla-17](https://user-images.githubusercontent.com/45978935/87859979-27e8b800-c8ff-11ea-87a3-635d76a9830b.png)

 - OS:  4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux

**Comment by ComplexRalex** [comment]
I think the problems are because the compiler didn't track well the src/ path. However, in the next commit, I made a lot of changes, including a catching NullPointerException and IllegalArgumentException in those places where is required. Thanks for the issue!

**Comment by ComplexRalex** [comment]
Now finally, there is a "run.sh" file inside the bin folder! Just be sure to run it in that same directory :D
